enum ButtonVariant {
  Default = "default",
  Primary = "primary",
  Dashed = "dashed",
  Text = "text",
  Link = "link",
}

export const menu = {
  leftSideButtons: [
    {
      text: "Ride",
      onclick: "",
      style: "",
      type: ButtonVariant.Text,
      haveSideMenu: false,
      sideMenu: "",
    },
    {
      text: "Earn",
      onclick: "",
      style: "",
      type: ButtonVariant.Text,
      sideMenu: [
        {
          text: "Drive",
          onclick: "",
          style: "",
          type: ButtonVariant.Text,
          haveSideMenu: false,
          sideMenu: "",
        },
        {
          text: "Deliver",
          onclick: "",
          style: "",
          type: ButtonVariant.Text,
          haveSideMenu: false,
          sideMenu: "",
        },
      ],
    },
    {
      text: "Business",
      onclick: "",
      style: "",
      type: ButtonVariant.Text,
      haveSideMenu: false,
      sideMenu: "",
    },
    {
      text: "Uber eats",
      onclick: "",
      style: "",
      type: ButtonVariant.Text,
      haveSideMenu: false,
      sideMenu: "",
    },
    {
      text: "About",
      onclick: "",
      style: "",
      type: ButtonVariant.Text,
      haveSideMenu: true,
      sideMenu: [
        {
          text: "About us",
          onclick: "",
          style: "",
          type: ButtonVariant.Text,
          sideMenu: "",
        },
        {
          text: "Our offering",
          onclick: "",
          style: "",
          type: ButtonVariant.Text,
          haveSideMenu: false,
          sideMenu: "",
        },
        {
          text: "How Uber Works",
          onclick: "",
          style: "",
          type: ButtonVariant.Text,
          haveSideMenu: false,
          sideMenu: "",
        },
        {
          text: "Sustainability",
          onclick: "",
          style: "",
          type: ButtonVariant.Text,
          haveSideMenu: false,
          sideMenu: "",
        },
        {
          text: "Explore",
          onclick: "",
          style: "",
          type: ButtonVariant.Text,
          haveSideMenu: true,
          sideMenu: [
            {
              text: "Cities",
              onclick: "",
              style: "",
              type: ButtonVariant.Text,
              haveSideMenu: true,
              sideMenu: [
                {
                  text: "Getting around Warsaw",
                  onclick: "",
                  style: "",
                  type: ButtonVariant.Text,
                  haveSideMenu: false,
                  sideMenu: "",
                },
                {
                  text: "Getting around Kraków",
                  onclick: "",
                  style: "",
                  type: ButtonVariant.Text,
                  haveSideMenu: false,
                  sideMenu: "",
                },
                {
                  text: "Getting around Poznań",
                  onclick: "",
                  style: "",
                  type: ButtonVariant.Text,
                  haveSideMenu: false,
                  sideMenu: "",
                },
                {
                  text: "Getting around Wrocław",
                  onclick: "",
                  style: "",
                  type: ButtonVariant.Text,
                  haveSideMenu: false,
                  sideMenu: "",
                },
                {
                  text: "Getting around Gdańsk",
                  onclick: "",
                  style: "",
                  type: ButtonVariant.Text,
                  haveSideMenu: false,
                  sideMenu: "",
                },
                {
                  text: "Getting around Katowice",
                  onclick: "",
                  style: "",
                  type: ButtonVariant.Text,
                  haveSideMenu: false,
                  sideMenu: "",
                },
              ],
            },
          ],
        },
        {
          text: "Newsroom",
          onclick: "",
          style: "",
          type: ButtonVariant.Text,
          haveSideMenu: false,
          sideMenu: "",
        },
        {
          text: "Investor relations",
          onclick: "",
          style: "",
          type: ButtonVariant.Text,
          haveSideMenu: false,
          sideMenu: "",
        },
        {
          text: "Autonomus",
          onclick: "",
          style: "",
          type: ButtonVariant.Text,
          haveSideMenu: false,
          sideMenu: "",
        },
        {
          text: "Blog",
          onclick: "",
          style: "",
          type: ButtonVariant.Text,
          haveSideMenu: false,
          sideMenu: "",
        },
        {
          text: "Careers",
          onclick: "",
          style: "",
          type: ButtonVariant.Text,
          haveSideMenu: false,
          sideMenu: "",
        },
      ],
    },
  ],
  rightSideButtons: [
    {
      text: "EN",
      onclick: "",
      style: "",
      type: ButtonVariant.Text,
      haveSideMenu: false,
      sideMenu: "",
    },
    {
      text: "Help",
      onclick: "",
      style: "",
      type: ButtonVariant.Text,
      haveSideMenu: false,
      sideMenu: "",
    },
    {
      text: "Log in",
      onclick: "",
      style: "",
      type: ButtonVariant.Text,
      haveSideMenu: false,
      sideMenu: "",
    },
    {
      text: "Sign up",
      onclick: "",
      style: "",
      type: ButtonVariant.Primary,
      haveSideMenu: false,
      sideMenu: "",
    },
  ],
};
